# Generated by Django 4.2.21 on 2025-06-29 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image2",
            field=models.ImageField(blank=True, null=True, upload_to="product_images/"),
        ),
        migrations.AddField(
            model_name="product",
            name="image3",
            field=models.ImageField(blank=True, null=True, upload_to="product_images/"),
        ),
    ]
